export enum PokemonsActionTypes {
  GET_ALL_POKEMONS = "GET_ALL_POKEMONS",
  SET_POKEMON = "SET_POKEMON",
  SEARCH_POKEMONS = "SEARCH_POKEMONS",
  GET_POKEMONS_START = "GET_POKEMONS_START",
  GET_POKEMON_SUCCESS = "GET_POKEMONS_SUCCESS",
  GET_POKEMON_FAILURE = "GET_POKEMONS_FAILURE",
}
